/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package lgpt-0.1.0.0 */
#ifndef VERSION_lgpt
#define VERSION_lgpt "0.1.0.0"
#endif /* VERSION_lgpt */
#ifndef MIN_VERSION_lgpt
#define MIN_VERSION_lgpt(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_lgpt */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package ansi-terminal-1.1.2 */
#ifndef VERSION_ansi_terminal
#define VERSION_ansi_terminal "1.1.2"
#endif /* VERSION_ansi_terminal */
#ifndef MIN_VERSION_ansi_terminal
#define MIN_VERSION_ansi_terminal(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_ansi_terminal */
/* package base-4.19.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.19.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package containers-0.6.8 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.8"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 8)
#endif /* MIN_VERSION_containers */
/* package http-conduit-2.3.9.1 */
#ifndef VERSION_http_conduit
#define VERSION_http_conduit "2.3.9.1"
#endif /* VERSION_http_conduit */
#ifndef MIN_VERSION_http_conduit
#define MIN_VERSION_http_conduit(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 9)
#endif /* MIN_VERSION_http_conduit */
/* package megaparsec-9.6.1 */
#ifndef VERSION_megaparsec
#define VERSION_megaparsec "9.6.1"
#endif /* VERSION_megaparsec */
#ifndef MIN_VERSION_megaparsec
#define MIN_VERSION_megaparsec(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_megaparsec */
/* package mtl-2.3.1 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.3.1"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 1)
#endif /* MIN_VERSION_mtl */
/* package time-1.12.2 */
#ifndef VERSION_time
#define VERSION_time "1.12.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_time */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.30.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.30.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "lgpt-0.1.0.0-1ANLwuohFmz58Pnaj4nZqS"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "lgpt-0.1.0.0-1ANLwuohFmz58Pnaj4nZqS"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
