name:                 lgpt
version:              0.1.0.0
visibility:           public
id:                   lgpt-0.1.0.0-BfDXyzMAEJA1xcLpLweCv2
key:                  lgpt-0.1.0.0-BfDXyzMAEJA1xcLpLweCv2
copyright:            2026 Alex Dixon
maintainer:           alexander.dixon@warwick.ac.uk
author:               Alex Dixon
description:
    The Lightly Generalised Parsing Task, a chatbot that can respond to requests in the terminal. Used as coursework for CS141 Functional Programming at the University of Warwick.

abi:                  c8bcd1a8ce3745b52320e46e4efc80ac
exposed:              True
exposed-modules:      LGPT.Helpers LGPT.Numbers LGPT.TUI
hidden-modules:       Paths_lgpt
import-dirs:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/lib/x86_64-linux-ghc-9.4.8/lgpt-0.1.0.0-BfDXyzMAEJA1xcLpLweCv2

library-dirs:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/lib/x86_64-linux-ghc-9.4.8/lgpt-0.1.0.0-BfDXyzMAEJA1xcLpLweCv2
    /modules/cs141/.stack-libs

library-dirs-static:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/lib/x86_64-linux-ghc-9.4.8/lgpt-0.1.0.0-BfDXyzMAEJA1xcLpLweCv2
    /modules/cs141/.stack-libs

dynamic-library-dirs:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/lib/x86_64-linux-ghc-9.4.8
    /modules/cs141/.stack-libs

data-dir:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/share/x86_64-linux-ghc-9.4.8/lgpt-0.1.0.0

hs-libraries:         HSlgpt-0.1.0.0-BfDXyzMAEJA1xcLpLweCv2
depends:
    aeson-2.2.3.0-Cuf9lDLZC3lHS0zvPaLsLb
    ansi-terminal-1.1.2-G1tJcHc6L8MH4W7tCk3Lu8 base-4.17.2.1
    containers-0.6.7 http-conduit-2.3.9.1-J71QDpOIuR02vjp03HIbjU
    megaparsec-9.6.1-ISqGNXtgP6xKRg8wIybxYu mtl-2.2.2 time-1.12.2

haddock-interfaces:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/doc/lgpt-0.1.0.0/lgpt.haddock

haddock-html:
    /dcs/25/u5683397/Documents/cs141/cw2/lgpt/.stack-work/install/x86_64-linux/2fcfeb28e342e22c83a6946cc3264c9633761ec0918683892cadfdcbb79e35d9/9.4.8/doc/lgpt-0.1.0.0
